### ISSUE TITLE
`termux-dialog` not working on Android 9

### ISSUE THREAD

**Issue by nenadilic84** [termux/termux-api#228]
I'm facing this issue on my oneplus 6.

I've already checked all the Termux:API permissions and all other commands I've tested are pretty much working properly expect the `termux-dialog` where it only locks down.

```
$ termux-info
Updatable packages:
All packages up to date
System information:
Linux localhost 4.9.106-perf+ #1 SMP PREEMPT Sat Sep 15 01:11:54 CST 2018 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
OnePlus
Device model:
ONEPLUS A6003
```
Battery status working:
```
$ termux-battery-status
{
  "health": "GOOD",
  "percentage": 89,
  "plugged": "PLUGGED_USB",
  "status": "CHARGING",
  "temperature": 29.200000762939453
}
```

```
$ termux-dialog
^C
```
Logcat output:
```
$ logcat -s termux:* termux-api:*
--------- beginning of crash
--------- beginning of main
```

I've tried to debug this with Android Studio but the issue I'm facing after compiling the Termux APK and Termux:API apk, is that my debugger doesn't know how to start the  Termux:API application as it is missing the main Activity.

Any help here would be appreciated in order to resolve it.

**Comment by nenadilic84** [comment]
It is related to the issue fixed here: https://github.com/termux/termux-api/pull/200

**Comment by xandro0777** [comment]
The same problem occurs also at least on Android 5.1 (#200).. wondering on which systems it works?

**Comment by laconbass** [comment]
This seems related to #207 , maybe problem is not specific to Android 9 P as seems affecting also 7.x and 6.x

**Comment by xandro0777** [comment]
Also affecting 5.1

**Comment by laconbass** [comment]
After full data + cache clean + uninstall both Termux and Termux:Api; and reinstalling both apps and `termux-api`, problem persists.

**Comment by laconbass** [comment]
Related:

- issue https://github.com/termux/termux-api/issues/168 and it's solution at PR https://github.com/termux/termux-app/pull/811
- issue https://github.com/termux/termux-packages/issues/334
- https://github.com/termux/termux-packages/issues/361 (old issue related to device-specific firmware) 
solved at httpss://github.com/termux/termux-packages/issues/361#issuecomment-260208178

**Comment by laconbass** [comment]
After manually enable of "access to notifications" for Termux API, `termux-info` does not terminate.

`termux-toast` also working now, but `termux-dialog` still hangs with:

```
01-29 21:10:53.882 23517 23517 D AndroidRuntime: >>>>>> START com.android.internal.os.RuntimeInit uid 10151 <<<<<<
01-29 21:10:54.046 23517 23517 E libc    : Access denied finding property "ro.vendor.at_library"
01-29 21:10:54.038 23517 23517 W main    : type=1400 audit(0.0:553): avc: denied { read } for name="u:object_r:vendor_mpctl_prop:s0" dev="tmpfs" ino=6391 scontext=u:r:untrusted_app:s0:c151,c256,c512,c768 tcontext=u:object_r:vendor_mpctl_prop:s0 tclass=file permissive=0
01-29 21:10:54.057 23517 23517 D AndroidRuntime: Calling main entry com.example.termuxam.Am
01-29 21:10:54.096 23517 23517 D AndroidRuntime: Shutting down VM
```

**Comment by xeffyr** [comment]
> did you guys test this after merging the PR.

Yes, it was tested.

![screenshot_20190129-224538_termuxapi](https://user-images.githubusercontent.com/25881154/51939294-c9343380-2417-11e9-9744-b6c7678d0903.jpg)

**Comment by laconbass** [comment]
After fiddling a bit, I can confirm the `E libc : Access denied finding property "ro.vendor.at_library"` error is triggered on almost any call to `iai-api` commands.

**Comment by laconbass** [comment]
@nenadilic84 Where can I find info to test your solution? I mean, packaging the native apps on my computer to install them.

**Comment by Quasic** [comment]
On my LG Android 5, it says Termux:API has stopped, but works on my LG Android 7.

**Comment by nenadilic84** [comment]
@laconbass, I've created a PR here. I usually build my APKs manually using the Android Studio. Thus I suggest you check out the branch, build it and run it. Please note that you also have to build the main Termux APK as well in order to have the same version. Hope this helps.

**Comment by laconbass** [comment]
I can confirm this commit fixed the issue on my setup. Thanks!

**Comment by Nahidnn** [comment]
~~~~
