### ISSUE TITLE
StorageGetApi failing with FLAG_ACTIVITY_NEW_TASK related error

### ISSUE THREAD

**Issue by slanglade** [termux/termux-api#285]
**Problem**
When calling termux-storage-get, nothing happens. When displaying traces using logcat, an error appears, related to FLAG_ACTIVITY_NEW_TASK. 

**Steps to reproduce**
On a fully patched Samsung s8 (stock and not rooted), after installing the needed termux components, this is systematic. 

**Expected behavior**
Should work OK : display a file selector and copy the selected file to the given destination. 

**Additional information**
Post output of command `termux-info`.
termux-info
Updatable packages:
All packages up to date
Subscribed repositories:
https://dl.bintray.com/grimler/science-packages-24 science/stable
https://dl.bintray.com/grimler/game-packages-24 games/stable
https://dl.bintray.com/termux/termux-packages-24 stable/main
System information:
Linux localhost 4.4.111-16290088 #1 SMP PREEMPT Wed Jun 26 16:57:13 KST 2019 aarch64 Android
Termux-packages arch:
aarch64
Android version:
9
Device manufacturer:
samsung
Device model:
SM-G950F

**Trace using logcat** 
08-20 18:15:25.056  8481  8481 D AndroidRuntime: Calling main entry com.example.termuxam.Am
08-20 18:15:25.131  8491  8491 E com.termux.api: Not starting debugger since process cannot load the jdwp agent.
08-20 18:15:25.254  8491  8506 E termux-api: Error in ResultReturner
08-20 18:15:25.254  8491  8506 E termux-api: android.util.AndroidRuntimeException: Calling startActivity() from outside of an Activity  context requires the FLAG_ACTIVITY_NEW_TASK flag. Is this really what you want?
08-20 18:15:25.254  8491  8506 E termux-api:   at android.app.ContextImpl.startActivity(ContextImpl.java:974)
08-20 18:15:25.254  8491  8506 E termux-api:   at android.app.ContextImpl.startActivity(ContextImpl.java:950)
08-20 18:15:25.254  8491  8506 E termux-api:   at android.content.ContextWrapper.startActivity(ContextWrapper.java:384)
08-20 18:15:25.254  8491  8506 E termux-api:   at android.content.ContextWrapper.startActivity(ContextWrapper.java:384)
08-20 18:15:25.254  8491  8506 E termux-api:   at com.termux.api.StorageGetAPI.lambda$onReceive$0(StorageGetAPI.java:31)
08-20 18:15:25.254  8491  8506 E termux-api:   at com.termux.api.-$$Lambda$StorageGetAPI$b8crtuQ3KGrGePkdr1kAiAN95Dw.writeResult(Unknown Source:4)
08-20 18:15:25.254  8491  8506 E termux-api:   at com.termux.api.util.ResultReturner.lambda$returnData$0(ResultReturner.java:118)

(I copied as much as possible from termux terminal) 

**Something strange** (maybe not related) : the Termux:API has no storage permission that I can give him, in app properties.

**Comment by slanglade** [comment]
Added comment : others functions seems to work OK (termux-dialog, termux-vibrate etc.)

**Comment by xalexalex** [comment]
The storage permission should be given to Termux, not Termux:API.

Can't reproduce on my device (Huawei PRA-LX1), but this is most likely related to #286 .

**Comment by xalexalex** [comment]
Could you please test more api functions, and report on which work and which don't? Another interesting info would be if they misbehave always or sometimes they work fine.

**Comment by xalexalex** [comment]
Cancel that, I managed to reproduce it and it should be fixed.
Meanwhile (until the next release is published) you should be able to bypass this problem by manually granting the storage permission to Termux.

**Comment by slanglade** [comment]
Hi,

Thanks for your work.

I checked the authorizations given to Termux : storage access is already granted to Termux. I also gave all possible permissions to Termux:API (caméra, contact, mic, phone and location) , but there is still the same behavior : termux:API call fail and termux terminal is stuck on the termux-storage-get call (Ctrl+c to quit and resume terminal).

Is there any specific test that I can do to help you?

**Comment by xalexalex** [comment]
My fault, I mixed up this issue and the other similar one. This issue will not be fixed by manually granting the storage permission to Termux; you'll have to wait for Termux:API v0.36 (a few hours in the Play Store, a few days in F-Droid).

**Comment by slanglade** [comment]
OK that's cool, thanks a lot.
